app = 'mine-scope-api'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3001'
  DB_PATH = '/data/mining.db'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'mine_scope_data'
  destination = '/data'
